---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipe-analysis-navigator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipe-analysis-navigator
  template:
    metadata:
      labels:
        app: pipe-analysis-navigator
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hsc-gen3repo
        persistentVolumeClaim:
          claimName: hsc-gen3repo-pvc
      - name: pgpass
        configMap:
          name: pgpass
      - name: pgpass-secrets-dir
        emptyDir: {}
      initContainers:
      - name: init
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        command:
        - /bin/bash
        - -c
        - cp /root/.pgpass /var/run/secrets/pgpass/.pgpass && chmod a+rw /var/run/secrets/pgpass/.pgpass
        volumeMounts:
        - name: pgpass
          mountPath: "/root/.pgpass"
          subPath: ".pgpass"
        - name: pgpass-secrets-dir
          mountPath: "/var/run/secrets/pgpass"
      containers:
      - name: pipe-analysis-navigator
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        command:
          - /bin/bash
          - -c 
          - panel serve dashboard_gen3.py --port {{ .Values.port | default 8080 }} --prefix {{ .Values.basePath }} --allow-websocket-origin {{ .Values.hostname }}
        volumeMounts:
        - name: hsc-gen3repo
          mountPath: /project/hsc/gen3repo
          readOnly: true
        - name: pgpass-secrets-dir
          mountPath: "/var/run/secrets/pgpass"
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  cp /var/run/secrets/pgpass/.pgpass /home/worker/.pgpass && \
                  rm /var/run/secrets/pgpass/.pgpass && \
                  chown worker:worker /home/worker/.pgpass && \
                  chmod go-rwx /home/worker/.pgpass
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgpass
data:
  .pgpass: |
    lsst-pg-prod1.ncsa.illinois.edu:5432:lsstdb1:svcplotnavigator:
