---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hsc-gen3repo-pv
spec:
  storageClassName: nfs-condo
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /user/staff/project/hsc/gen3repo
    server: radiant-nfs.ncsa.illinois.edu
    readOnly: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hsc-gen3repo-pvc
spec:
  volumeName: hsc-gen3repo-pv
  storageClassName: nfs-condo
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
