---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pipetask-plot-navigator
spec:
  selector:
    app: {{ .Release.Name }}-pipetask-plot-navigator
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.port | default 8080 }}
